public class SalesforceDeveloper {
    public void myFirstCode(){

        string favoriteCity ='Rome';
        string favoriteFilm = 'Braveheart';
        string favoriteSeason = 'Spring';

        system.debug('my Favorite city is  '+ favoriteCity);
        system.debug(' my Favoriye film is '+ favoriteFilm);
        system.debug('my Favorite season is '  + favoriteSeason);
    }

    public void myFavorites(){
        Integer favoriteNumber=25;
        string city = 'Austin';

        system.debug( 'My favorite number '+ favoriteNumber);
        system.debug('My city is '+ city);
    }

}
